### ISSUE TITLE
Distinguishing between v2 and v1 on the website.

### ISSUE THREAD

**Issue by jgOhYeah** [spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2#3]
Hello,
Would it be possible to put a note on the website (http://www.cosmicwatch.lns.mit.edu/detector#steps) about this version because I (and maybe a few other people) keep getting the versions confused as I cannot find any reference to this version other than through the facebook page and pdf (https://arxiv.org/pdf/1801.03029.pdf). Maybe I am just not looking properly.
Thanks.

**Comment by spenceraxani** [comment]
Hi,

Thanks for the comment, we have plans to update the website fairly soon to reflect the changes in v2.

Spencer

**Comment by jgOhYeah** [comment]
Thanks
