### ISSUE TITLE
Can the power supply impact the count?

### ISSUE THREAD

**Issue by jimgallatin** [spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2#39]
Spencer,

I just noticed that my count fluxuates with the power supply I use.  For example, when I plug the detector into my professor’s Mac the counts sink down to .250.  When I plug it into a wall socket or my Mac the counts rise to .422.  I will be building a second Detector as you suggested but thought this might be relevant to my low counts (beyond the likelihood of a less effective scintillator).

Jim

**Comment by jimgallatin** [comment]
Spencer,

I took the detector home again and it is now running at .250 Hz regardless of power source.  Weird. I was able to download data to Python.

Jim

**Comment by spenceraxani** [comment]
Hi Jim,

I think there’s probably something still wrong with your detector. I think building a second one might shed light on what the issue is.

Thanks,

Spencer

**Comment by jimgallatin** [comment]
That I am sure of!  Thanks.  Will do.

**Comment by jimgallatin** [comment]
😎

**Comment by jimgallatin** [comment]
Count on defective detector back up to .400s.  Building new detector today.  Closing this out.
