### ISSUE TITLE
Coincidence mode count rate

### ISSUE THREAD

**Issue by pedelen** [spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2#41]
When connected in coincidence mode the count on the slave device is running about 0.15 signals per sampling time when connected and viewed on the Cosmic Watch site. Is this a reasonable value to expect? It is far lower than the signal rate when each device is monitored independently.

**Comment by spenceraxani** [comment]
Hi,

If the two detectors are sitting on top of each other this is a completely reasonable rate.

Thanks,

Spencer

**Comment by pedelen** [comment]
Hi,

 

Yes the two detectors are sitting on top of each other. Thank you for the feedback.

 

Paul
