### ISSUE TITLE
Incorrect Digikey Part Number in "Purchasing List.xlsx"

### ISSUE THREAD

**Issue by claudepi** [spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2#59]
Hello,

I believe that Item # 15 in the Detector Purchasing List in "Purchasing List.xlsx" has the incorrect Digikey part number:

Item 15 
10nF capacitor
4	
$0.03	
CAP CER 10000PF 50V X7R 0805	
Digikey Part Number: 276-2563-1-ND

That comes up on Digikey as a 10 pF capacitor. I believe the correct item is a 10 nF capacitor with Digikey part number 311-1136-1-ND. Note that "SMT_reference.pdf" has the Digikey correct part number listed. 

Thank you,
Seth

**Comment by spenceraxani** [comment]
Hi Seth,

Thanks! I’ve updated the list. 

Spencer
