### ISSUE TITLE
Unable to upload Arduino Code to Arduino Nano Every

### ISSUE THREAD

**Issue by Draconum** [spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2#66]
Hi,

I am using an Arduino Nano Every and whenever I attempt to upload the code up to it, it displays the message 'ADSCRA was not declared in this scope".  I've downloaded all the drivers required and they all seem to function and I've copied and pasted the code as provided however this issue still persists. Does the fact that the Arduino Nano Every is classified as Ardunio megaAVR board affect this?

Also, I'm able to upload the Name file, just not the OLED.

Thanks!

**Comment by spenceraxani** [comment]
Hi,

I haven’t used the Every board, so I don’t think I can say too much about this error. The lines of code related to “ADCSRA” are modifying the prescaler to increase the ADC sampling rate (~10us/sample). This would be a necessary update to the code that you’ll need to implement. Without it, the default sampling rate it too slow and you’ll end up missing many pulses or perhaps trigger on the tails of pulses.

I’m not sure how to implement it on the Every board, but it should be possible with a bit of digging online.

Thanks,

Spencer
