### ISSUE TITLE
1 count and then no detection

### ISSUE THREAD

**Issue by halifaxjack** [spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2#73]
Hi Spencer, 

I'm new to electronics and am learning a lot as I go through this project, so thank you for making this.

I've assembled 2 detectors and am getting the same 1 count error on both of them. I'm getting the correct voltages according to the instructions, and my SiPM is giving resistance. I've played around with your code and changed the thresholds but still get the 1 count error.

Here are some pictures of my hardware, incase it's an assembly issue.
![20220105_121059](https://user-images.githubusercontent.com/97195260/148286970-737af7b0-0a95-4c97-b96a-1731b3faef82.jpg)
![20220105_121903](https://user-images.githubusercontent.com/97195260/148286974-b3980fed-0ac6-4689-a975-bd8ecb8f6854.jpg)
![20220105_122145](https://user-images.githubusercontent.com/97195260/148286975-c62f29be-88cc-45b1-a748-b917be973b71.jpg)
![20220105_122216](https://user-images.githubusercontent.com/97195260/148286976-19bb8e65-969c-43f0-84f8-b0fef63fce5a.jpg)
![20220105_122224](https://user-images.githubusercontent.com/97195260/148286980-f9feb832-1c29-4762-9bc0-cddfe2e6e7f3.jpg)

Cheers,
And thanks again!

Jack

**Comment by spenceraxani** [comment]
Hi Jack,

Thanks for the nice images. One thing that pops out is the lack of tape or tape residual on your SiPM PCB. I’d like to first confirm that you are wrapping the whole SiPM PCB assembly in black tape before booting it up. It will have to be light tight to work.

Your solder joints look well done, although there is likely a cold solder or poor connection somewhere. This tends to be the most likely issue, so I would start there — hit every solder joint with some new solder to ensure a good connection. For example, it looks like one of the legs on the op amp may not be connected (image below). R3 looks OK, but could also be suspect.

If the above two things do not solve your problem, can you remove the temperature sensor? Twice in the past month-or-so I saw people with faulty sensors.

Finally, if you are changing the thresholds, I would increase them. Maybe bring them both up to ~60 ADC counts.

Thanks,

Spencer

**Comment by halifaxjack** [comment]
Hi Spencer, 

Thanks! I hit a few joints with some extra solder and light tightened by SiPM PCB and its working now! Now I need to increase that threshold because I'm getting some crazy counts.

Cheers 
Jack

**Comment by spenceraxani** [comment]
Glad to hear it. I would keep the threshold at the default value. Perhaps you have a light leak? You really need it to be light-tight. The count rate should be single Hz level.
